name: "test"

on:
  push:

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "ubuntu:latest"
            platform: "linux/amd64"
          - image: "ghcr.io/tetratelabs/func-e-internal:centos8"
            platform: "linux/amd64"
          - image: "arm64v8/fedora:latest"
            platform: "linux/arm64"
    steps:
      - run: docker run ${{ matrix.image }} ls
