name: "test"

on:
  push:

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM: "ubuntu-latest"
          - FROM: "arm64v8/fedora:latest"
          - FROM: "ghcr.io/tetratelabs/func-e-internal:centos8"
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.FROM }}
          run: uname -a

