name: "test"

on:
  push:

jobs:
  test:
    name: "Test packaging build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          # ubuntu is missing wixl https://github.com/actions/virtual-environments/issues/3857
          - os: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Set up emulation
        if: runner.os == 'Linux'
        run:  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: "Test"
        if: runner.os == 'Linux'
        uses: docker://arm64v8/ubuntu
        with:
          args: packaging/nfpm/verify_deb.sh
