name: "test"

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        include:
          - dockerfile: |
              FROM centos:8
              RUN yum install -y --quiet make which git gcc && yum clean all
            target-tag: centos8
          - dockerfile: |
              FROM ubuntu:latest
            target-tag: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          cat > Dockerfile <<'EOF'
          ${{ matrix.dockerfile }}
          EOF
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.target-tag }}

  # test:
  #   name: "Test packaging build (${{ matrix.os }})"
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false  # don't fail fast as sometimes failures are operating system specific
  #     matrix:
  #       include:
  #         # ubuntu is missing wixl https://github.com/actions/virtual-environments/issues/3857
  #         - os: ubuntu-latest

  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2

  #     - name: "Test installing Debian package (Ubuntu)"
  #       if: runner.os == 'Linux'
  #       # Running dpkg and apt-get requires "sudo".
  #       run: sudo packaging/nfpm/verify_deb.sh

  #     - name: "Test installing RPM package (Centos 8 via ghcr.io/tetratelabs/func-e-internal:centos8)"
  #       if: runner.os == 'Linux'
  #       uses: docker://ghcr.io/tetratelabs/func-e-internal:centos8
  #       with:
  #         # Since we use the root user here, it does not require "sudo".
  #         args: packaging/nfpm/verify_rpm.sh

  #     - name: "Set up QEMU"
  #       if: runner.os == 'Linux'
  #       uses: docker/setup-qemu-action@v1
  #       with:
  #         platforms: arm64

  #     - name: "Test arm"
  #       if: runner.os == 'Linux'
  #       uses: docker://arm64v8/ubuntu
  #       with:
  #         args: packaging/nfpm/verify_deb.sh arm64

  #     - name: "Test aarch"
  #       if: runner.os == 'Linux'
  #       uses: docker://arm64v8/centos
  #       with:
  #         args: packaging/nfpm/verify_rpm.sh aarch64
