name: "test"

on:
  push:

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: docker://ghcr.io/tetratelabs/func-e-internal:centos8
      - name: "ok"
        run: uname -a

