name: "test"

on:
  push:

jobs:
  linux-amd64:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "ubuntu:latest"
            platform: "linux/amd64"
          - image: "ghcr.io/tetratelabs/func-e-internal:centos8"
            platform: "linux/amd64"
    steps:
      - run: docker run ${{ matrix.image }} ls

  linux-non-amd64:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "aarch64"
            distro: "fedora_latest"
    steps:
      - uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          run: uname -a
