name: "test"

on:
  push:

jobs:
  test:
    name: "Test packaging build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          # ubuntu is missing wixl https://github.com/actions/virtual-environments/issues/3857
          - os: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: "Test"
        if: runner.os == 'Linux'
        run: sudo packaging/nfpm/verify.sh
        env:
          DEB_FILE: dist/func-e_dev_linux_arm64.deb
