name: "test"

on:
  push:

jobs:
  linux-amd64:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "ubuntu:latest"
            arch: amd64
            packaging: deb
          - image: "ghcr.io/tetratelabs/func-e-internal:centos8"
            arch: rpm
            packaging: rpm

    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run -e ARCH=${{ matrix.arch }} \
            -e PACKAGING=${{ matrix.packaging }} \
            -v ${{ github.workspace }}:/src \
            -w /src \
            ${{ matrix.image }} \
            ./verify.sh

  linux-non-amd64:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "aarch64"
            distro: "fedora_latest"
            packaging: "rpm"
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          env: |
            ARCH: ${{ matrix.arch }}
            PACKAGING: ${{ matrix.packaging }}
          dockerRunArgs: |
            --volume "${PWD}:/src" -w /src
          run: ./verify.sh
