name: "test"

on:
  push:

jobs:
  test:
    name: "Test packaging build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          # ubuntu is missing wixl https://github.com/actions/virtual-environments/issues/3857
          - os: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Test installing Debian package (Ubuntu)"
        if: runner.os == 'Linux'
        # Running dpkg and apt-get requires "sudo".
        run: sudo packaging/nfpm/verify_deb.sh

      - name: "Test installing RPM package (Centos 8 via ghcr.io/tetratelabs/func-e-internal:centos8)"
        if: runner.os == 'Linux'
        uses: docker://ghcr.io/tetratelabs/func-e-internal:centos8
        with:
          # Since we use the root user here, it does not require "sudo".
          args: packaging/nfpm/verify_rpm.sh
