name: "test"

on:
  push:

jobs:
  test:
    name: "Test packaging build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          - os: ubuntu-latest
    steps:
      - name: "Test run in container"
        if: runner.os == 'Linux'
        uses: docker://ghcr.io/tetratelabs/func-e-internal:centos8
        with:
          args: /bin/sh -c "`pwd`"
