name: "test"

on:
  push:

jobs:
  build-and-push-images:
    strategy:
      matrix:
        include:
          - dockerfile: |
              FROM centos:8
              RUN yum install -y --quiet make which git gcc && yum clean all
            target-tag: centos8
          - dockerfile: |
              FROM ubuntu:20.04
            target-tag: ubuntu20.04
    runs-on: ubuntu-latest
    steps:
      - name: Login into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Write Dockerfile for ${{ matrix.target-tag }}
        run: |
          cat > Dockerfile <<'EOF'
          ${{ matrix.dockerfile }}
          EOF

      - name : Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # Build and push for multiple architectures.
          tags:  ghcr.io/${{ github.repository_owner }}/random-images:${{ matrix.target-tag }}

      # We do re-tagging for easier usage when using emulation. Using `uses: docker://` only allows
      # to override `args`, but not the --platform flag (tried using `options` but no luck). Reference:
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-the-github-packages-container-registry.
      # Related: https://github.com/actions/virtual-environments/issues/1368.
      - name : Re-tag for arm64 only
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64 # Build and push for arm64 architecture only.
          tags:  ghcr.io/${{ github.repository_owner }}/random-images:${{ matrix.target-tag }}-arm64
